# version: '3.8'

# services:
#   nginx:
#     image: nginx:alpine
#     ports:
#       - "8080:80"      # expose Nginx load balancer on host port 8080
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#     depends_on:
#       - server
#   server:
#     build: ./server
#     expose:
#       - "3000"         # exposes port 3000 to other containers only
#     environment:
#       - PORT=3000      # if your app needs this env var

# version: '3.8'
# services:
#   server1:
#     build: ./server
#     ports:
#       - "3001:3000"
#     environment:
#       - SERVER_NAME=Server1
#   server2:
#     build: ./server
#     ports:
#       - "3002:3000"
#     environment:
#       - SERVER_NAME=Server2
#   server3:
#     build: ./server
#     ports:
#       - "3003:3000"
#     environment:
#       - SERVER_NAME=Server3
#   nginx:
#     image: nginx:alpine
#     ports:
#       - "8080:80"      # expose Nginx load balancer on host port 8080
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#     depends_on:
#       - server1
#       - server2
#       - server3



# version: '3.8'

# services:
#   nginx:
#     image: nginx:alpine
#     ports:
#       - "8080:80"      # expose Nginx load balancer on host port 8080
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#     depends_on:
#       - server
#   server:
#     build: ./server
#     expose:
#       - "3000"         # exposes port 3000 to other containers only
#     environment:
#       - PORT=3000      # if your app needs this env var

version: '3.8'
services:
  server1:
    build: ./server
    expose:
      - "3000"
    environment:
      - SERVER_NAME=Server1
    networks:
      - internal
  server2:
    build: ./server
    expose:
      - "3000"
    environment:
      - SERVER_NAME=Server2
    networks:
      - internal
  server3:
    build: ./server
    expose:
      - "3000"
    environment:
      - SERVER_NAME=Server3
    networks:
      - internal
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"      # expose Nginx load balancer on host port 8080
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - internal
  
networks:
  internal: {}